### ISSUE TITLE
O projeto não compila 

### ISSUE THREAD

**Issue by CHEATSGAMES** [elDimasX/Free-Fire-Full-Regedit#1]
Eu extrai os arquivos packages assim como fui instruido, e sempre que vou compilar aparece estes erros:
![image](https://user-images.githubusercontent.com/90113744/178369712-e77ab5f2-e0b0-4420-80dd-008d61809c54.png)
![image](https://user-images.githubusercontent.com/90113744/178369844-a9f60f37-c6dd-4e73-b76f-76f505864bd7.png)

**Comment by elDimasX** [comment]
Obrigado por avisar, já estou trabalhando em uma atualização que resolverá tudo.

**Comment by Sp1ky1** [comment]
@CHEATSGAMES Drop guna.ui on the source along with packages and it will compile just fine
